### ISSUE TITLE
proposta di modifica CSS

### ISSUE THREAD

**Issue by aborruso** [italia/docs-italia-starter-kit#1]
Buongiorno,
ho visto in [azione lo starter kit](http://linee-guida-open-data-comune-palermo.readthedocs.io/it/latest/) mi sembra che nella sidebar ci sia da rimuovere quello spazio non utilizzato, e riempirlo meglio allineando a sinistra.

Che ne pensat? Io per ora non posso dare una mano con il CSS e mi limito stavolta soltanto alla proposta.

Lo vedo come sotto sia su chrome che su firefox, su un monitor di circa 1300x800 px.

Grazie

![immagine](https://user-images.githubusercontent.com/30607/37394818-fd3d95b8-2774-11e8-87e1-f79065c21a17.png)

**Comment by francescozaia** [comment]
Ciao @aborruso mi trovi assolutamente d'accordo e, a tal proposito, abbiamo già una issue aperta a riguardo: https://github.com/italia/docs-italia-theme/issues/47, che speriamo di prendere in carico al più presto!

**Comment by alterat** [comment]
Ma questo problema dipende da particolari browser o risoluzioni dello schermo? Perché a me, personalmente, non è mai capitato...

**Comment by cirospat** [comment]
stamattina in ufficio, mentre inserivo i contenuti nelle pagine .RST (risoluzione monitor 1366 x 1080) lo vedevo perfetto.

Ora a casa nel laptop 16 pollici, (risoluzione schermo 1366 x 768) lo vedo come lo vede @aborruso, (allego screenshot), quindi con una parte a sinistra vuota, che in effetti da fastidio perchè il testo si restringe inutilmente.

![image](https://user-images.githubusercontent.com/3757525/37428168-b2eef7b6-27cb-11e8-806f-da643d22c64d.png)

**Comment by alterat** [comment]
Confermo il problema di Ciro e Andrea quando la finestra è molto larga. 

<img width="400" alt="bar" src="https://user-images.githubusercontent.com/19559470/37428574-9239b35a-27c4-11e8-9fb4-e61091a1374e.png">

Il problema potrebbe essere dato dalla dicitura "Downloads" che compare in basso a sinistra, facendo aumentare il margine? Forse basta eliminare quella?

**Comment by cirospat** [comment]
@atorin si potrebbe fare la prova ad eliminare la dicitura "Downloads" e vedere il risultato

**Comment by aborruso** [comment]
@cirospat  hai ragione, è proprio download e il suo stile che rompe tutto, perché si prende spazio in aree non "sue"

![immagine](https://user-images.githubusercontent.com/30607/37431044-61ba9fcc-27d4-11e8-964d-40d8923afae2.png)

**Comment by ruphy** [comment]
@aborruso Grazie della segnalazione, direi che è decisamente un problema da risolvere. Se avete voglia di scrivere del codice a riguardo (e aprire una PR) ovviamente è molto apprezzato! 😄

**Comment by aborruso** [comment]
@ruphy grazie a te. Come ho scritto però nel messaggio di segnalazione a questo giro sono un po' out.
Ma nel caso, ritorno

**Comment by francescozaia** [comment]
La versione più recente del tema sistema, tra le varie cose, anche questo problema; è usato ad esempio dalla [linee guida di design](http://design-italia.readthedocs.io/it/stable/).
È inoltre in fase di sviluppo un nuovo tema, completamente rivisto e conforme alle nuove linee guida.
