### ISSUE TITLE
Campo "logo"

### ISSUE THREAD

**Issue by francescozaia** [italia/docs-italia-starter-kit#11]
Nello starter kit, il campo "logo" è innestato dentro "assets", ma questa inclusione non è indicata nella guida.
Alla luce del fatto che (almeno per ora) non sono necessari altri assets, potremmo semplicemente rimuovere `assets` e portarlo al primo livello.
Opinioni @atorin? Grazie

**Comment by alterat** [comment]
Intendi, spostare `logo.svg` a livello dei due file yml?

**Comment by francescozaia** [comment]
Perdonami non so scrivere, intendevo proprio portare il campo allo stesso livello di `name`, `description` ecc.:
```
publisher:
  name: ...
  logo: wherever/logo.svg
```

**Comment by alterat** [comment]
Ah d'accordo! Sì, ha più senso fare come proponi tu.

**Comment by alterat** [comment]
@francescozaia questa issue possiamo chiuderla, giusto?

**Comment by francescozaia** [comment]
Giusto!
