### ISSUE TITLE
Nuova struttura dei files per Docs Italia

### ISSUE THREAD

**Issue by danse** [italia/docs-italia-starter-kit#8]
in italia/docs-italia-comandi-conversione#31 abbiamo definito le strutture ideali dei files `.rst` nei casi di documenti più o meno complessi. Possiamo ora aggiornare i files qui contenuti in modo che seguano la nuova convenzione

**Comment by alterat** [comment]
@danse 
Allora per lo starter kit usiamo la _struttura lineare_ di cui parlava @pdavide in italia/docs-italia-comandi-conversione#31, siamo d'accordo?
